main: main.lisp positionUtils.lisp matrix.lisp readpuzzle.lisp validations.lisp certainSolutions.lisp solve.lisp solveRegion.lisp
	clisp -c main.lisp

execute: main.fas
	clisp main.fas

clean: 
	rm -rf *.lib *.fas